### ISSUE TITLE
Add security group attribute when creating CCE2 Nodes

### ISSUE THREAD

**Issue by Valdm** [terraform-providers/terraform-provider-flexibleengine#132]
### Terraform Version
`Terraform v0.11.11`

### Affected Resource(s)
- CCE2 Nodes auto-generated Security groups

### Expected Behavior
Export an security group (id/name) attribute when creating an CCE2 Cluster nodes to retrieves the security group generated

### Actual Behavior
Any information about security groups for nodes in ressources or data.

### Steps to Reproduce
`Deploy a CCE2 cluster with nodes`

**Comment by niuzhenguo** [comment]
@Valdm Thanks for raising this, but can you be able to specify that on GUI, I don't find we have a security group parameter with CCE API.

**Comment by Valdm** [comment]
Thanks for your reply. We are not able to specify a security group for the CCE Node on the GUI, and with the CCE API also.

**Comment by niuzhenguo** [comment]
@Valdm So, maybe you should create an issue on the cloud side instead of here :)

**Comment by WayneFromHuawei** [comment]
Hello @Valdm 

In order to understand your point clearly.

 I firstly align between us about the current security group policy on CCE cluster, which is as described in the online help doc:
![sg-cce](https://user-images.githubusercontent.com/29310205/53725179-c213a180-3e6b-11e9-9f89-b5cb2cae51ad.JPG)
As you can notice: there are two security groups created automatically, one for the master nodes and another for the worker nodes. and when you create a new worker node independently, you don't need to specify the security group proactively, it  will associate the already existing security group for the worker nodes to that node automatically. ]]


so what you required is to have the security group(ID or Name) visible on the console(action through GUI) when adding a new node? (purpose is to know which SG it is using exactly then you can easily link to see/update the  details/rules of the SG)
or 
you need to specify your own security group to the nodes? (what's the purpose here if in this case?)

**Comment by Valdm** [comment]
Hello @WayneFromHuawei, 

Thanks for your reply.

I know that two different security groups are created automatically when creating a CCE Cluster. 
In my use case, the purpose is to build a CCE and also other components (RDS, ECS etc..) automatically with Terraform (Terragrunt especially) without human intervention (Like retrieve the security group id of nodes in the GUI before injecting it on the second terraform plan).

So, my needs are (1 or 2) : 
1. Specify my own security group to the nodes when creating CCE Cluster
OR
2. Retrieve the security group ID generated when the cluster has been created.

-- 

@niuzhenguo Thanks. I'll put an issue on the Cloud side instead.

**Comment by antonin-a** [comment]
Hello,

My two cents: solution two look more fancy and appropriate. 

-> Adding SecGroups IDs to CCE Datasources

**Comment by WayneFromHuawei** [comment]
@Valdm @antonin-a 
thanks for clarification, i agree with Antonin
to export SG ID/Name in both Datasource and Attributes Reference after cluster created. (as Valdm also suggested in the thread)

will push on this.

**Comment by antonin-a** [comment]
Hello, FYI deployment is under progress on Flexible Engine side so we will soon (expected for July) have the APIs providing the secgroup ID when creating the cluster.

**Comment by Gwenael22** [comment]
Hello @antonin-a , any news concerning this feature ?
The lastest CCE deployment does not include this parameter (cf. CCE API doc in version 2019-07-30)

**Comment by antonin-a** [comment]
Hello,
The secGroup ID is now returned when executing the Obtaining CCE cluster info API call (https://docs.prod-cloud-ocb.orange-business.com/en-us/api/cce/en-us_topic_0035621933.html) 
Now we need to update the TF provider to use those new parameters, @niuzhenguo are you already working on this ? To have have an expected delivery date ?

**Comment by niuzhenguo** [comment]
@antonin-a The next release will be the end of Sep, will make sure this included.
